name: Daily Knowledge Update
on:
  schedule:
    - cron: "0 2 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run collectors
        run: python backend/collectors/run_all.py
      - name: Commit updates
        run: |
          git config user.name "AI-Bot"
          git config user.email "ai@bot.com"
          git add backend/collectors/*
          git commit -m "Daily knowledge update"
          git push
